### ISSUE TITLE
Questions on SDK and FlutterWave

### ISSUE THREAD

**Issue by flexpeace** [Flutterwave/rave-python#20]
We are currently working with Access Bank in Ghana, and we would like to use this SDK. I can see that it is in serious development. Below are my questions 

1. Can we use it in production?
2. Does the SDK allow payments from Europe, Asia and America?
3. What cards do you support? Is it only Visa and MasterCard?
4. Can we use Mpesa to accept payments from clients in Kenyan even though my company is registered in Ghana?
5. Can we use the SDK to disburse money to Bank accounts in Nigeria?

Thanks and l will be on Standby for your response

**Comment by MaestroJolly** [comment]
Hi @flexpeace ,

1. It is already available for use in production.
2. Yes it does, you can receive payments in these currencies: NGN, GHS, KES, UGX, USD, EUR, ZAR, TZS, and GBP. For more details on this, please refer to this link: https://support.flutterwave.com/article/151-receive-currencies.
3.We support all Mastercards and Visa cards for now.
4. Yes you can accept Mpesa payments from clients in Kenya.
5. Yes you can also use it to Transfer/Disburse Funds to Bank Accounts.

You can use the SDK to perform all of the above and more.

Regards.

**Comment by ernest-andela** [comment]
Thanks l have further questions.

1. I realized the OTP message is not sent  when using the sandboxapi?
2. Also, is there a way to stop the confirmation email to our Rave registered email? Because if we are processing 10000 transactions a day, we wouldn't want our inbox to be flooded with emails?
3. Also, do you send a confirmation email to the customer? if yes, can we disable this so we can send a customized confirmation email to the client?
4. I realized when using the test cards, the expiry year, CVC are not checked only the card number?

**Comment by flexpeace** [comment]
Thanks l have further questions.

1. I realized the OTP message is not sent  when using the sandboxapi?
2. Also, is there a way to stop the confirmation email to our Rave registered email? Because if we are processing 10000 transactions a day, we wouldn't want our inbox to be flooded with emails?
3. Also, do you send a confirmation email to the customer? if yes, can we disable this so we can send a customized confirmation email to the client?
4. I realized when using the test cards, the expiry year, CVC are not checked only the card number?

**Comment by MaestroJolly** [comment]
1. OTP message wouldn't be sent on sandbox or test environment, you can find all test card details with OTP on this link: https://developer.flutterwave.com/v2.0/reference#test-cards-1

2. Yes you can disable the messages sent by rave if you don't want to be receiving transaction emails. You can do this under settings: https://ravesandbox.flutterwave.com/dashboard/settings/accounts

3. You can also disable the messages sent to customers if you want to create your own customized emails from the settings page.

4. The test cards are only created for test environments, all cards credentials would be checked on live environment.

5. You can register the bank account you want to be settled in any bank available on rave, please refer to this link to know more about settlements by country: https://support.flutterwave.com/article/153-settlement-schedule

**Comment by flexpeace** [comment]
I have more questions:

1. Is the pin always a number (int) or it can contain text? Where can the user find the pin? Do they create these pin by themselves?

2. Is the address verification only for Cards in USA? if not, is State required for other countries which do not have state?

3. Does your platform accept credit card?

**Comment by MaestroJolly** [comment]
1. Pin is the card pin and it is always in digits.

2. Yes, Address Verification is for cards in US.

3. Yes we accept credit card.

4. The status indicates a transaction that wasn't validated after a period and it gets logged to the dashboard.

5. Whenever a customer enters an incorrect pin, an error is thrown i.e the transaction will not proceed

6. There are three validation process: 
- With OTP
- 3DSecure
- Noauth

Whenever the response above is returned with an authUrl, it means the customer is required to authenticate/validate the transaction from the authUrl returned in the response. This indicates a typical 3Dsecure transaction

You can also refer to this link: https://developer.flutterwave.com/reference#card-payments to further understand this.

**Comment by flexpeace** [comment]
Thanks for your reply.

I didn't quite understand point number 6. So the below is an example of which of the Validations. I validated the PIN and then l got the response below and l can see  'validationRequired': True. So my question is, which of the validation is required for the response below?  Clicking on https://ravesandboxapi.flutterwave.com/mockvbvpage?re
f=FLW-MOCK-682eb2f3308c208b9ae4a66fc167c253&code=00&message=Approved returns a JSON response. Do l need to embed this URL in an iframe https://ravesandboxapi.flutterwave.com/mockvbvpage?re
f=FLW-MOCK-682eb2f3308c208b9ae4a66fc167c253&code=00&message=Approved returns a JSON response.

```
{'error': False, 'validationRequired': True, 'txRef': 'Sz2Mb3RhfygQ-1551
772889.4955368', 'flwRef': 'FLW-MOCK-682eb2f3308c267c253', 'suggest
edAuth': None, 'authUrl': 'https://ravesandboxapi.flutterwave.com/mockvbvpage?re
f=FLW-MOCK-682eb2f3308c208b9ae4a66fc167c253&code=00&message=Approved. Successful
&receiptno=RN1551772898631'}
```

Also, after reading this URL https://developer.flutterwave.com/reference#rave-encryption. Does the python SDK automatically encrypt the request or l have to do it manually?

**Comment by MaestroJolly** [comment]
@flexpeace , 

There's are different ways to handle transaction authentication on rave which are,

- OTP - This will be sent to the card holder's phone number
- 3DSecure - An auth url will be received in the response which needs to be loaded where the authentication would be done by the customer
- and Noauth - No auth mean the card would be charged automatically without any further authentication

just as explained on this link: https://developer.flutterwave.com/reference#card-payments, You just need to be watching out for the suggested auth returned in the response, The SDK already handles this though, you just need to go through it and understand it.

For encryption: You don't need to do any encryption again, the SDK already handles this for you, if not, you wouldn't have been able to get this response:

```
{'error': False, 'validationRequired': True, 'txRef': 'Sz2Mb3RhfygQ-1551
772889.4955368', 'flwRef': 'FLW-MOCK-682eb2f3308c267c253', 'suggest
edAuth': None, 'authUrl': 'https://ravesandboxapi.flutterwave.com/mockvbvpage?re
f=FLW-MOCK-682eb2f3308c208b9ae4a66fc167c253&code=00&message=Approved. Successful
&receiptno=RN1551772898631'}
```

Please you can also check our sample app here: https://github.com/MaestroJolly/python_sample_apps, to get idea on how some of these things work.

**Comment by flexpeace** [comment]
Thanks. I am closing this

**Comment by finkcloud** [comment]
I'm using rave for the first time, it looked so flexible and easier to integrate, but along the line. I got stuck with testing, I'm using only card and bank payments methods
**1.** when I choose the card to and enter some test cards from the test card link https://developer.flutterwave.com/reference#test-cards-1 
I get 2 errors, => "unable to retrieve transaction fees" but in my logcat I see => " only test cards ree allowed," of which were using the test cards. And am also on staging mode which I assume is correct while testing with test keys.

**2. When I use the bank tab**
i get some error in JSON toasted, but display later => "parents_limit not defined"  
not just that I give this errors, I still found transactions of the bank payment types recorded on my dashboard. 
this confuses me more since I didn't get the payment success message so I can verify and give value to the customer.

please help me with a workaround I'm stuck and have no time to deliver this.

**Comment by MaestroJolly** [comment]
hi @finkcloud, 

- Kindly share the test card that you are currently using for this test.

- Please confirm if this issue is still happening, if yes, share a screenshot.

**Comment by Orsunmigbare** [comment]
@MaestroJolly kindly help on how I can retry a failed transfer(payout) having the "reference"?  I searched the docs but can't seem to find help.. a link will also be appreciated. thanks 🙏

**Comment by Kyeza** [comment]
Hello, I have a backend that accept MTN Mobile money and it had been working but recently when a client initiate a payment they receive an OTP with this message inclusive "MOMO Verification Auth", yet the expected behaviour is initiate a pin input box where the user enters the Mobile money pin to initiate payment, @MaestroJolly, could you offer any help please

below is my implementation
```
from rave_python import Rave, RaveExceptions

rave = Rave(settings.RAVE_PUBLIC_KEY, settings.RAVE_SECRET_KEY, production=True)

payload = {
  "txRef": "67865",
  "flwRef": "flwm3s4m0c1523183355860",
  "amount": "34000",
  "email": "rave@rave.com",
  "user_phonenumber": "256784660058",
  "phonenumber": "256784660058",
  "firstname": "Jeffrey",
  "lastname": "Jeffrey",
  "redirect_url": "",
  "device_id": "sadsdadweqweqe",
  "IP": ""
}

try:
    try:
        response = rave.UGMobile.charge(payload)
    except RaveExceptions.TransactionChargeError as e:
        print(e.err)
        print(e.err["flwRef"])
        return Response(e.err, status=status.HTTP_400_BAD_REQUEST)
    except RaveExceptions.TransactionVerificationError as e:
        print(e.err["errMsg"])
        print(e.err["txRef"])
        return Response(e.err, status=status.HTTP_400_BAD_REQUEST)
except KeyError as e:
    print(f'missing key: {e.args}')
```

I keep get this as my error: 
"**flwRef = responseJson["data"]["flwRef"]
KeyError: 'flwRef'**"

**Comment by narendragpt** [comment]
How can i use this SDK for custom ui can any one provide the steps.
And also I need to all custom UI like Bank details page,Card pin , OTP page??
