### ISSUE TITLE
Failed to initiate a USSD on phone

### ISSUE THREAD

**Issue by ssekuwanda** [Flutterwave/rave-python#23]
After making a payload as a dictionary and passing it into charge
res = rave.UGMobile.charge(payload)
I get a dic with status of success nad chargemessage as pending Payment validation but no USSD notification to enter password

**Comment by anjolabassey** [comment]
hi, @ssekuwanda  are u on live or test mode. also, can u share your payload here

**Comment by temiadesina** [comment]
This is a telco issue, the number was not enabled for STK push.
