### ISSUE TITLE
Refactor rave_account.py

### ISSUE THREAD

**Issue by siarheipuhach** [Flutterwave/rave-python#55]
Refactoring of codebase required to be in python style depending on [PEP-8](https://www.python.org/dev/peps/pep-0008/). Start from `rave_account.py`

**Comment by Official-kornelios** [comment]
rave_account.py has been refactored according to python style depending on PEP-8. This closes #55

**Comment by Official-kornelios** [comment]
@siarheipuhach please close this issue. your PR has been merged.
