### ISSUE TITLE
IP not required

### ISSUE THREAD

**Issue by Uncensored-Developer** [Flutterwave/rave-python#66]
On rave pay documentation the IP address is not required so it shouldn't be required to charge a card with the SDK to.

**Comment by Corvus97** [comment]
Hello @Uncensored-Developer,

Thanks for the feedback.

We have deployed a fix to address the issue you raised. In the new update, only the params listed as required in the documentation are made compulsory in the SDK.

Please feel free to check out the update and let us know what you think about it.

We are excited to hear from you soon.

Kind regards,
Cornelius.
