### ISSUE TITLE
Instance of Rave has no "Card" member

### ISSUE THREAD

**Issue by teejayfamo** [Flutterwave/rave-python#73]
All classes imported into rave.py are not available for use directly. Prime example is that I get the prompt **Instance of Rave has no "Card" member** when I use **rave.Card** after Initialisation.

## Describe the Bug

Following the documentation, on importing and initialising Rave, I observed that I had an error stating that the instance of Rave had no member "Card". Further investigation showed that the problem also affects all other classes imported into the rave. That prevents me from doing anything related to card payments, accounts etc. I looked through rave.py and rave_card.py. I can't spot any error yet.
## System Information

 - Operating system: Windows 10
 - Rave version: Current Version

**Comment by Corvus97** [comment]
Hello @teejayfamo,

Thanks for bringing this to the attention of the Team.

Kindly be advised that the error reported is a linting error and does not affect the functionality of the SDK.

The team is looking into fixing the linting error. In the meantime, kindly help confirm if the SDK is fully functional at your end.

We look forward to hearing from you.

Best regards,
Cornelius.
