### ISSUE TITLE
Charge in Francophone mobile money not working for Central Africa(Cameroon, Gabon, etc)

### ISSUE THREAD

**Issue by RogersNtr** [Flutterwave/rave-python#79]
Hi all, 
We have tried for many days now to integrate Gabon, Cameroon mobile money Payment in our flow. But nothing is working. Cameroon doesn't even appear in the dropdown menu when using flutterwave standard API. 
Charges directly using the charges endpoint, also didn't succeed. 

Are you available in XAF currency based countries ? because I don't even know what to try next.
Your sincerely.

**Comment by Corvus97** [comment]
Hello Rogers,

We deeply apologise for the experience.

Kindly shoot us an email at developers@flutterwavego.com if you are still experiencing the issue reported.

We are eager to help you resolve it as soon as possible.

Best regards,
Cornelius.
