### ISSUE TITLE
Invalid transaction attempt. No REF Cache

### ISSUE THREAD

**Issue by KengoWada** [Flutterwave/rave-python#83]
When I try to validate a card payment, I get the above response and I don't know how to deal with it.

**Comment by Corvus97** [comment]
Hello @KengoWada,

Thanks for bringing this to our attention.

Kindly be informed that this error is returned when the reference verified is wrong/non-existent. Please cross-check your transaction reference and retry the verification call.

If you require more assistance, you can contact us on our developer forum, https://developer.flutterwave.com/discuss

Regards,
Cornelius
