### ISSUE TITLE
No module named 'rave_python'

### ISSUE THREAD

**Issue by comfortchambeshi** [Flutterwave/rave-python#85]
I was trying to test flutterwave python SDK. Now i got this error:
`from rave_python import Rave, RaveExceptions, Misc

ModuleNotFoundError: No module named 'rave_python'`

**Comment by sheyzi** [comment]
Hope you installed it correctly.... And if you are using a virtual env make sure you had installed it in the virtual env

**Comment by Br3mah** [comment]
**Run this:**
pip install rave-python

**Instead of:**
pip install rave_python

**Comment by comfortchambeshi** [comment]
> pip install rave-python

Still not working!

**Comment by Corvus97** [comment]
Hello @comfortchambeshi ,

Please note that this is a linting error raised by your IDE.

Kindly ignore and proceed with your development.

Rest assured the team is working on removing the error.

Regards,
