### ISSUE TITLE
Invalid public key

### ISSUE THREAD

**Issue by sheyzi** [Flutterwave/rave-python#86]
Even after adding my public key as copied from the my dashboard it still tells me invalid public key

```
rave = Rave("FLWPUBK-201208a9c0d71279795e96fb2ed7a133-X", "MY SECRET KEY WAS HERE", usingEnv = False)
```

**Comment by Br3mah** [comment]
Try to generate and use new rave test keys

**Comment by Corvus97** [comment]
Please pass the production flag as true and retry the initialization.
