### ISSUE TITLE
uganda mobile money payment keyError: 'txRef'

### ISSUE THREAD

**Issue by phibi3** [Flutterwave/rave-python#90]
i get this error when ever i try to process payment

**Comment by Corvus97** [comment]
Hi @phibi3,

Please share your payload here.

**Comment by Corvus97** [comment]
Hello @phibi3 ,

The verify method has been updated across all MoMO classes.

This issue has been resolved.

**Comment by Kamal-Moha** [comment]
I'm facing this same issue.

Here is the payload I'm running

```
# mobile payload
payload = {
  "amount": "10000",
  "email": "cornelius@example.com",
  "phonenumber": "07********",#"123456789",
  "redirect_url": "https://mtn.com",
  "IP":"102.209.256.256",
  "network": "MTN"
}

try:
  res = rave.UGMobile.charge(payload)
  ver = rave.UGMobile.verify(res["txRef"])
  print(ver)

except RaveExceptions.TransactionChargeError as e:
  print(e.err)
  print(e.err["flwRef"])

except RaveExceptions.TransactionVerificationError as e:
  print(e.err["errMsg"])
  print(e.err["txRef"])
```

When I run the above code, I get this error;
`KeyError: 'txRef'`

When I investigate further and do `print(res)`, I see this dict;
`{'error': False, 'status': 'success', 'message': 'Momo initiated', 'code': '02', 'transaction status': 'pending', 'ts': 1766129739272, 'link': 'https://checkout-v2.dev-flutterwave.com/captcha/verify/lang-en/204748:3ed7dc178eaf337ea28f4406ba8a651c'}`

I see the dict doesn't have a txRef key which is causing the error. What am I doing wrong??
